/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghSetFreqPage;
extern GHandle ghStartCalibration;
extern GHandle ghStartRace;
extern GHandle ghLabel1;
extern GHandle ghLabel2;
extern GHandle ghLabel3;
extern GHandle ghLabel4;
extern GHandle ghConsole1;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

