/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle ghSetFreqPage;
GHandle ghStartCalibration;
GHandle ghStartRace;
GHandle ghLabel1;
GHandle ghLabel2;
GHandle ghLabel3;
GHandle ghLabel4;
GHandle ghConsole1;

// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_32;

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// create button widget: ghSetFreqPage
	wi.g.show = TRUE;
	wi.g.x = 190;
	wi.g.y = 10;
	wi.g.width = 120;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "Change Freq";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghSetFreqPage = gwinButtonCreate(0, &wi);

	// create button widget: ghStartCalibration
	wi.g.show = TRUE;
	wi.g.x = 190;
	wi.g.y = 50;
	wi.g.width = 120;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "Start Calib";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghStartCalibration = gwinButtonCreate(0, &wi);

	// create button widget: ghStartRace
	wi.g.show = TRUE;
	wi.g.x = 190;
	wi.g.y = 90;
	wi.g.width = 120;
	wi.g.height = 30;
	wi.g.parent = ghContainerPage0;
	wi.text = "Start Race";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghStartRace = gwinButtonCreate(0, &wi);

	// Create label widget: ghLabel1
	wi.g.show = TRUE;
	wi.g.x = 120;
	wi.g.y = 190;
	wi.g.width = 200;
	wi.g.height = 40;
	wi.g.parent = ghContainerPage0;
	wi.text = "00:00:00";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel1, FALSE);
	gwinSetFont(ghLabel1, dejavu_sans_32);
	gwinRedraw(ghLabel1);

	// Create label widget: ghLabel2
	wi.g.show = TRUE;
	wi.g.x = 120;
	wi.g.y = 170;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Best lap time";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel2, FALSE);

	// Create label widget: ghLabel3
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 190;
	wi.g.width = 100;
	wi.g.height = 40;
	wi.g.parent = ghContainerPage0;
	wi.text = "00:00";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel3 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel3, FALSE);
	gwinSetFont(ghLabel3, dejavu_sans_32);
	gwinRedraw(ghLabel3);

	// Create label widget: ghLabel4
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 170;
	wi.g.width = 80;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Timer";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel4 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel4, FALSE);

	// Create console widget: ghConsole1
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 10;
	wi.g.width = 170;
	wi.g.height = 150;
	wi.g.parent = ghContainerPage0;
	ghConsole1 = gwinConsoleCreate(0, &wi.g);
	gwinSetColor(ghConsole1, black_studio);
	gwinSetBgColor(ghConsole1, silver_studio);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_32 = gdispOpenFont("DejaVuSans32");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

	// Console sample text
	gwinPrintf(ghConsole1, "Welcome to MRaceTimer");
}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}

	}
}

